apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoservice1-k8s
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demoservice1-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: demoservice1-k8s
    spec:
      containers:
      - name: demoservice1-k8s
        image: mastercloudapps/demoservice1-k8s
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demoservice1-k8s
  labels:
    app: demoservice1-k8s
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: demoservice1-k8s-port
  selector:
    app: demoservice1-k8s
  type: NodePort