version: "3.9"
services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=db
      - MONGODB_PORT=27017
      - MONGODB_COLLECTION=posts
    depends_on:
      - db
  db:
    image: mongo:5.0.6-focal
    volumes:
      - ./mongo:/data/db