apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: ubuntu
    name: test-container
    command: ["/bin/bash", "-ec", "sleep 30"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}